//
//  main.c
//  URLEncoder
//
//  Created by Volker Bach on 13.08.12.
//  Copyright (c) 2012 Volker Bach. All rights reserved.
//

#include <CoreFoundation/CoreFoundation.h>

int main(int argc, const char * argv[])
{
    
    if (argc < 2) {
        return 1;
    }
    
    CFMutableStringRef encodedString;
    CFStringRef argStr = CFStringCreateWithCString( NULL, argv[1], kCFStringEncodingUTF8 );
    encodedString = CFStringCreateMutableCopy(NULL, 0, argStr);
    CFRelease(argStr);
    CFStringFindAndReplace(encodedString, CFSTR("%20"), CFSTR(" "), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%21"), CFSTR("!"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%22"), CFSTR("\""), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%23"), CFSTR("#"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%24"), CFSTR("$"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%25"), CFSTR("%"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%26"), CFSTR("&"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%27"), CFSTR(""), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%28"), CFSTR("("), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%29"), CFSTR(")"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%2A"), CFSTR("*"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%2B"), CFSTR("+"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%2C"), CFSTR(","), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%2D"), CFSTR("-"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%2E"), CFSTR("."), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%2F"), CFSTR("/"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%30"), CFSTR("0"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%31"), CFSTR("1"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%32"), CFSTR("2"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%33"), CFSTR("3"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%34"), CFSTR("4"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%35"), CFSTR("5"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%36"), CFSTR("6"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%37"), CFSTR("7"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%38"), CFSTR("8"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%39"), CFSTR("9"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%3A"), CFSTR(":"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%3B"), CFSTR(";"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%3C"), CFSTR("<"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%3D"), CFSTR("="), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%3E"), CFSTR(">"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%3F"), CFSTR("?"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%40"), CFSTR("@"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%41"), CFSTR("A"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%42"), CFSTR("B"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%43"), CFSTR("C"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%44"), CFSTR("D"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%45"), CFSTR("E"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%46"), CFSTR("F"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%47"), CFSTR("G"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%48"), CFSTR("H"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%49"), CFSTR("I"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%4A"), CFSTR("J"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%4B"), CFSTR("K"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%4C"), CFSTR("L"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%4D"), CFSTR("M"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%4E"), CFSTR("N"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%4F"), CFSTR("O"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%50"), CFSTR("P"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%51"), CFSTR("Q"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%52"), CFSTR("R"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%53"), CFSTR("S"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%54"), CFSTR("T"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%55"), CFSTR("U"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%56"), CFSTR("V"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%57"), CFSTR("W"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%58"), CFSTR("X"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%59"), CFSTR("Y"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%5A"), CFSTR("Z"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%5B"), CFSTR("["), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%5C"), CFSTR("\\"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%5D"), CFSTR("]"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%5E"), CFSTR("^"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%5F"), CFSTR("_"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%60"), CFSTR("`"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%61"), CFSTR("a"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%62"), CFSTR("b"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%63"), CFSTR("c"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%64"), CFSTR("d"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%65"), CFSTR("e"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%66"), CFSTR("f"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%67"), CFSTR("g"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%68"), CFSTR("h"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%69"), CFSTR("i"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%6A"), CFSTR("j"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%6B"), CFSTR("k"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%6C"), CFSTR("l"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%6D"), CFSTR("m"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%6E"), CFSTR("n"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%6F"), CFSTR("o"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%70"), CFSTR("p"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%71"), CFSTR("q"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%72"), CFSTR("r"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%73"), CFSTR("s"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%74"), CFSTR("t"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%75"), CFSTR("u"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%76"), CFSTR("v"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%77"), CFSTR("w"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%78"), CFSTR("x"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%79"), CFSTR("y"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%7A"), CFSTR("z"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%7B"), CFSTR("{"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%7C"), CFSTR("|"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%7D"), CFSTR("}"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%7E"), CFSTR("~"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%7F"), CFSTR(" "), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%80"), CFSTR("`"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%81"), CFSTR(" "), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%82"), CFSTR("‚"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%83"), CFSTR("ƒ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%84"), CFSTR("„"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%85"), CFSTR("…"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%86"), CFSTR("†"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%87"), CFSTR("‡"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%88"), CFSTR("ˆ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%89"), CFSTR("‰"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%8A"), CFSTR("Š"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%8B"), CFSTR("‹"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%8C"), CFSTR("Œ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%8D"), CFSTR(" "), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%8E"), CFSTR("Ž"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%8F"), CFSTR(" "), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%90"), CFSTR(" "), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%91"), CFSTR(""), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%92"), CFSTR(""), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%93"), CFSTR("“"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%94"), CFSTR("”"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%95"), CFSTR("•"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%96"), CFSTR("–"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%97"), CFSTR("—"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%98"), CFSTR("˜"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%99"), CFSTR("™"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%9A"), CFSTR("š"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%9B"), CFSTR("›"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%9C"), CFSTR("œ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%9D"), CFSTR(" "), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%9E"), CFSTR("ž"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%9F"), CFSTR("Ÿ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A0"), CFSTR(" "), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A1"), CFSTR("¡"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A2"), CFSTR("¢"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A3"), CFSTR("£"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A4"), CFSTR("¤"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A5"), CFSTR("¥"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A6"), CFSTR("¦"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A7"), CFSTR("§"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A8"), CFSTR("¨"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%A9"), CFSTR("©"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%AA"), CFSTR("ª"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%AB"), CFSTR("«"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%AC"), CFSTR("¬"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%AD"), CFSTR("­"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%AE"), CFSTR("®"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%AF"), CFSTR("¯"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B0"), CFSTR("°"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B1"), CFSTR("±"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B2"), CFSTR("²"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B3"), CFSTR("³"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B4"), CFSTR("´"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B5"), CFSTR("µ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B6"), CFSTR("¶"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B7"), CFSTR("·"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B8"), CFSTR("¸"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%B9"), CFSTR("¹"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%BA"), CFSTR("º"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%BB"), CFSTR("»"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%BC"), CFSTR("¼"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%BD"), CFSTR("½"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%BE"), CFSTR("¾"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%BF"), CFSTR("¿"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C0"), CFSTR("À"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C1"), CFSTR("Á"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C2"), CFSTR("Â"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C3"), CFSTR("Ã"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C4"), CFSTR("Ä"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C5"), CFSTR("Å"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C6"), CFSTR("Æ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C7"), CFSTR("Ç"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C8"), CFSTR("È"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%C9"), CFSTR("É"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%CA"), CFSTR("Ê"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%CB"), CFSTR("Ë"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%CC"), CFSTR("Ì"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%CD"), CFSTR("Í"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%CE"), CFSTR("Î"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%CF"), CFSTR("Ï"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D0"), CFSTR("Ð"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D1"), CFSTR("Ñ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D2"), CFSTR("Ò"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D3"), CFSTR("Ó"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D4"), CFSTR("Ô"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D5"), CFSTR("Õ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D6"), CFSTR("Ö"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D7"), CFSTR("×"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D8"), CFSTR("Ø"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%D9"), CFSTR("Ù"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%DA"), CFSTR("Ú"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%DB"), CFSTR("Û"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%DC"), CFSTR("Ü"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%DD"), CFSTR("Ý"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%DE"), CFSTR("Þ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%DF"), CFSTR("ß"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E0"), CFSTR("à"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E1"), CFSTR("á"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E2"), CFSTR("â"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E3"), CFSTR("ã"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E4"), CFSTR("ä"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E5"), CFSTR("å"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E6"), CFSTR("æ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E7"), CFSTR("ç"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E8"), CFSTR("è"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%E9"), CFSTR("é"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%EA"), CFSTR("ê"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%EB"), CFSTR("ë"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%EC"), CFSTR("ì"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%ED"), CFSTR("í"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%EE"), CFSTR("î"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%EF"), CFSTR("ï"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F0"), CFSTR("ð"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F1"), CFSTR("ñ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F2"), CFSTR("ò"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F3"), CFSTR("ó"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F4"), CFSTR("ô"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F5"), CFSTR("õ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F6"), CFSTR("ö"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F7"), CFSTR("÷"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F8"), CFSTR("ø"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%F9"), CFSTR("ù"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%FA"), CFSTR("ú"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%FB"), CFSTR("û"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%FC"), CFSTR("ü"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%FD"), CFSTR("ý"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%FE"), CFSTR("þ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFStringFindAndReplace(encodedString, CFSTR("%FF"), CFSTR("ÿ"), (CFRange){0,CFStringGetLength(encodedString)}, 0);
    CFShow(encodedString);
    CFRelease(encodedString);
    return 0;
}

